sudo: required

language: c

services:
  - docker

compiler:
  - clang
  - gcc

env:
  - DISTRO=fedora:rawhide
  - DISTRO=fedora:24
  - DISTRO=fedora:23
  - DISTRO=centos:7
  - DISTRO=debian:unstable
  - DISTRO=debian:testing
  - DISTRO=ubuntu:devel
  - DISTRO=ubuntu:xenial
  - DISTRO=ubuntu:wily

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e CC=$CC
    $DISTRO /bin/bash -ex .travis.test $DISTRO
